# Generated by Django 6.0.1 on 2026-02-04 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['closing_date']},
        ),
        migrations.AddField(
            model_name='job',
            name='closing_date',
            field=models.DateField(default=datetime.date(2026, 2, 4), help_text='Job will disappear after this date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='short_description',
            field=models.TextField(default=datetime.date(2026, 2, 4)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description_file',
            field=models.FileField(blank=True, null=True, upload_to='jobs/descriptions/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/posters/'),
        ),
    ]
