# Generated by Django 6.0.1 on 2026-02-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_service_description_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
    ]
