# Generated by Django 6.0.1 on 2026-02-03 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contactsubmission_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Select a parent service to create a mini-service', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mini_services', to='store.service'),
        ),
    ]
