# Generated by Django 6.0.1 on 2026-02-04 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_service_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mini_services', to='store.service'),
        ),
    ]
