# Generated by Django 6.0.1 on 2026-02-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_service_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='nomination_form',
            field=models.FileField(blank=True, help_text='Upload nomination form (PDF/DOC)', null=True, upload_to='events/nominations/'),
        ),
        migrations.AddField(
            model_name='event',
            name='training_pdf',
            field=models.FileField(blank=True, help_text='Upload training materials (PDF)', null=True, upload_to='events/training/'),
        ),
    ]
