# Generated by Django 6.0.1 on 2026-02-06 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_event_nomination_form_event_training_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the event (link to Service)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='store.service'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of attending the event (leave blank if free)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Venue or location of the event', max_length=255, null=True),
        ),
    ]
