# Generated by Django 6.0.1 on 2026-02-10 07:44

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_event_category_event_cost_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='contact_attachments/', validators=[store.validators.validate_document_file]),
        ),
    ]
