# Generated by Django 6.0.1 on 2026-02-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_contactsubmission_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
